-- スキーマ定義

CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `groups` (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE events (
	id VARCHAR(255) PRIMARY KEY NOT NULL,
	user_id VARCHAR(255) NOT NULL,
	together BOOLEAN NOT NULL,
	description VARCHAR(255) NOT NULL,
	year INT NOT NULL,	
	month INT NOT NULL,
	day INT NOT NULL,
    date DATETIME NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	start_date DATETIME NOT NULL,
	end_date DATETIME NOT NULL,
    important BOOLEAN NOT NULL,
	CONSTRAINT foreign_key_products_user_id FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE group_users (
    group_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_group_users_group FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_users_user FOREIGN KEY (user_id) REFERENCES `users` (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE group_events (
    group_id VARCHAR(255) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (group_id, event_id),
    CONSTRAINT fk_group_events_group FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_events_event FOREIGN KEY (event_id) REFERENCES `events` (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE user_events (
    user_id VARCHAR(255) NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, event_id),
    CONSTRAINT fk_user_events_user FOREIGN KEY (user_id) REFERENCES `users` (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_events_event FOREIGN KEY (event_id) REFERENCES `events` (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
