// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthUserResponse struct {
	Token string `json:"token"`
	User  *User  `json:"User"`
}

type CreateEventInput struct {
	UserID      string `json:"userId"`
	Together    bool   `json:"together"`
	Description string `json:"description"`
	Year        int32  `json:"year"`
	Month       int32  `json:"month"`
	Day         int32  `json:"day"`
	Important   bool   `json:"important"`
}

type CreateGroupInput struct {
	Name   string `json:"name"`
	UserID string `json:"userId"`
}

type CreateItemInput struct {
	Name    string `json:"name"`
	GroupID string `json:"groupID"`
}

type CreateUserInput struct {
	LastName  string `json:"lastName"`
	FirstName string `json:"firstName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type DailyEventInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
	Day   int32 `json:"day"`
}

type Event struct {
	ID          string    `json:"id"`
	UserID      string    `json:"userID"`
	Together    bool      `json:"together"`
	Description string    `json:"description"`
	Year        int32     `json:"year"`
	Month       int32     `json:"month"`
	Day         int32     `json:"day"`
	Date        time.Time `json:"date"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	StartDate   time.Time `json:"startDate"`
	EndDate     time.Time `json:"endDate"`
	Important   bool      `json:"important"`
}

type EventRules struct {
	UserID         string `json:"userID"`
	ItemID         string `json:"itemID"`
	NormalLimit    int32  `json:"normalLimit"`
	ImportantLimit int32  `json:"importantLimit"`
}

type Group struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserIDs   []string  `json:"userIDs"`
	EventIDs  []string  `json:"eventIDs"`
}

type Item struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	GroupID string `json:"groupID"`
}

type MonthlyEventInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateGroupInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateUserInput struct {
	LastName  *string `json:"lastName,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
}

type UpsertEventRuleInput struct {
	UserID         string `json:"userID"`
	ItemID         string `json:"itemID"`
	NormalLimit    int32  `json:"NormalLimit"`
	ImportantLimit int32  `json:"ImportantLimit"`
}

type User struct {
	ID        string    `json:"id"`
	LastName  string    `json:"lastName"`
	FirstName string    `json:"firstName"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	GroupIDs  []string  `json:"groupIDs"`
	EventIDs  []string  `json:"eventIDs"`
}
